import 'package:sqflite/sqflite.dart';


class TableCreate
{  

  createtable0(Database db, int versiyon) async {
        await db.execute('CREATE TABLE Tanimlar('
        'key TEXT,'
        'value TEXT,'
        'groupname TEXT'
        ')');

    await db.execute('CREATE TABLE Kasa('
        'kod TEXT,'
        'sorumlu TEXT,'
        'kredi_karti_kasasi INTEGER'
        ')');

    await db.execute('CREATE TABLE CariSube('
        'r_sayac INTEGER,'
        'cari_sayac INTEGER,'
        'sube_kodu TEXT,'
        'sube_adi TEXT '
        ')');

    await db.execute('CREATE TABLE CariRut('
        'kod TEXT,'
        'gun TEXT,'
        'aktif INTEGER,'
        'gun_sira INTEGER,'
        'rut_sira_no INTEGER,'
        'aktifnoktasayisi INTEGER,'
        'pasifnoktasayisi INTEGER,'
        'rutSayac INTEGER,'
        'rutDetaySayac INTEGER,'
        'bugun INTEGER'
        ')');
        

    await db.execute('CREATE TABLE Cari('
        'r_sayac INTEGER,'
        'cari_tipi TEXT,'
        'cid TEXT,'
        'kod TEXT,'
        'kodu2 TEXT,'
        'unvan TEXT,'
        'semt TEXT,'
        'cari_adsoyad TEXT,'
        'temsilci_kodu TEXT,'
        'temsilci_adsoyad TEXT,'
        'tl_borc REAL ,'
        'tl_alacak REAL,'
        'tl_abakiye REAL,'
        'tl_bbakiye REAL,'
        'calisilan_borc REAL,'
        'calisilan_alacak REAL,'
        'calisilan_abakiye REAL,'
        'calisilan_bbakiye REAL,'
        'calisilan_tur TEXT,'
        'risk_tipi TEXT,'
        'risk_tipi_islem_durduruldu TINYINT,'
        'vergi_no TEXT,'
        'risk_limiti REAL,'
        'ust_kanal_kodu TEXT,'
        'kanal_kodu TEXT,'
        'alt_kanal_kodu TEXT,'
        'ust_kanal_adi TEXT,'
        'kanal_adi TEXT,'
        'alt_kanal_adi TEXT,'
        'musteri_tipi TEXT,'
        'efatura_kullanicisi TINYINT,'
        'sehir TEXT,'
        'ilce TEXT,'
        'satis_bolge_kodu TEXT,'
        'satis_bolge_adi TEXT,'
        'yetkili TEXT,'
        'tabela TEXT,'
        'e_mail TEXT,'
        'gunlukSiparisTutar REAL,'
        'gunlukFaturaTutar REAL,'
        'gunlukTahsilatTutar REAL,'
        'enlem TEXT,'
        'boylam TEXT'
        ')');
  }

  createtable1(Database db, int versiyon) async {
    await db.execute('CREATE TABLE CariVadeFarki('
          'Id INTEGER,'
          'cari_kodu  TEXT,'
          'cari_unvan TEXT,'
          'fatura_no INTEGER,'
          'islem_tipi TEXT,'
          'fis_tarihi DATETIME,'
          'vade_gun_sayisi INTEGER,'
          'vade_tarihi DATETIME,'
          'borc_alacak REAL,'
          'tefat_tutari REAL,'
          'tefat_bakiye_tutari REAL,'
          'bakiye_toplami REAL,'
          'tahsilat_gecikti TEXT,'
          'gecikme_gunu INTEGER,'
          'son_bakiye_bakod TEXT'
          ')');

    await db.execute('CREATE TABLE CariHesapEkstresi('
        'Id INTEGER,'
        'cari_kodu TEXT,'
        'cari_unvan TEXT,'
        'evrak_tarihi DATETIME,'
        'fis_no TEXT,'
        'resmi_belge_no TEXT,'
        'aciklama TEXT,'
        'vade_tarihi DATETIME,'
        'borc REAL ,'
        'alacak REAL ,'
        'bakiye REAL ,'
        'bakiye_borc_alacak TEXT,'
        'fis_turu TEXT'
        ')');

    await db.execute('CREATE TABLE CariAylikSatis('
        'id INTEGER,'
        'ay_str TEXT,'
        'malzeme_kodu TEXT,'
        'malzeme_adi TEXT,'
        'birim TEXT,'
        'dist_stok_kodu TEXT,'
        'malzeme_sinifi_adi TEXT,'
        'malzeme_sinifi_id TEXT,'
        'path TEXT,'
        'ay INTEGER,'
        'ciro REAL,'
        'miktar REAL,'
        'cari_kodu TEXT '        
        ')');
        
    await db.execute('CREATE TABLE Tahsilat('
        'r_sayac INTEGER PRIMARY KEY AUTOINCREMENT,'
        'cid TEXT,'
        'temsilci_kodu TEXT,'
        'cari_kodu TEXT,'
        'tarih DATETIME,'
        'kasa TEXT,'
        'fiyat REAL,'
        'fis_tur TEXT,'
        'mut_no TEXT,'        
        'mut_no2 TEXT,'
        'mut_no3 TEXT,'
        'slipno TEXT,'
        'kartno INTEGER,'
        'android_gps_sayac INTEGER,'
        'aciklama TEXT'        
        ')');
    }

  createtable2(Database db, int versiyon) async {
        await db.execute('CREATE TABLE Ziyaret('
        'id INTEGER PRIMARY KEY AUTOINCREMENT,'        
        'start_date DateTime,'
        'end_date DateTime,'
        'start_longitude REAL,'
        'start_latitude REAL,'
        'end_longitude REAL,'
        'end_latitude REAL,'
        'cari_kodu TEXT,'        
        'is_ziyaret_active INTEGER,'
        'rut_detay_sayac INTEGER,'
        'rut_detay_gun INTEGER,'
        'fatura_toplam REAL,'
        'siparis_toplam REAL,'
        'tahsilat_toplam REAL,'
        'ziyaret_tipi_sayac INTEGER,'
        'ziyaret_sonlandirma_tipi_sayac INTEGER,'
        'aciklama TEXT,'
        'aktarildi INTEGER,'
        'uzak_siparis INTEGER '
        ')');
        
      await db.execute('CREATE TABLE ZiyaretTipleri('
        'r_sayac INTEGER,'
        'tipi TEXT,'
        'aciklama TEXT '          
        ')');


      await db.execute('CREATE TABLE ZiyaretSonlandirmaTipleri('
        'r_sayac INTEGER,'
        'tipi TEXT,'
        'aciklama TEXT,'
        'sira INTEGER,'
        'sabit INTEGER,'
        'auto INTEGER,'
        'satisvar INTEGER,'
        'zorunlu_aciklama INTEGER '        
        ')');

    await db.execute('CREATE TABLE SatisAlisKontrol('
        'r_sayac INTEGER,'
        'birim_fiyat_degistir INTEGER,'
        'gen_iskonto_degistir INTEGER,'
        'satir_iskonto_degistir INTEGER,'
        'borc_kapatma INTEGER,'
        'fat_basimi_yapilsin INTEGER,'
        'fat_seri_no TEXT,'
        'odeme_tarih_hesapla INTEGER,'
        'sak_kullanim_sekli INTEGER,'
        'sak_tablosu TEXT,'

        'toplu_mal_ayirma INTEGER,'
        'irsaliye_basimi INTEGER,'
        'irsaliye_seri_no TEXT,'
        'siparis_yapilsin INTEGER,'

        'kamyonlastirma_yapilsin INTEGER,'
        'irsaliye_yapilsin INTEGER,'
        'fatura_yapilsin INTEGER,'
        'kontrol_no TEXT,'
        'aciklama TEXT,'
        'vade_degistir INTEGER,'

        'sts_irs_seri_no_rsayac INTEGER,'
        'sts_irs_basili_form_rsayac INTEGER,'
        'sts_fat_seri_no_rsayac INTEGER,'
        'sts_fat_basili_form_rsayac INTEGER,'
        'sts_fat_irs_basili_form_rsayac INTEGER,'
        'sts_iade_irsaliye_basimi INTEGER,'
        'sts_iade_irs_seri_no_rsayac INTEGER,'
        'sts_iade_irs_basili_form_rsayac INTEGER,'
        'sts_iade_fatura_basimi INTEGER,'
        'sts_iade_fat_seri_no_rsayac INTEGER,'
        'sts_iade_fat_basili_form_rsayac INTEGER '
        ')');      
        
    await db.execute('CREATE TABLE SatisTipleri('
        'r_sayac INTEGER,'
        'satis_tip_id TEXT,'
        'satis_tipi TEXT,'
        'aciklama TEXT,'
        'hareket_tipi_id TEXT,'
        'sak_kontrol_no TEXT,'
        'fiyat_tipi TEXT,'
        'depo_no TEXT,'
        'tesis_no TEXT,'
        'stok_tipi_no TEXT,'
        'iade_hareket_tipi_id TEXT,'
        'fatura_tipi_id TEXT,'
        'kampanyalari_otomatik_uygula INTEGER,'
        'iade INTEGER,'
        'goster INTEGER,'        
        'tablo_no TEXT,'
        'alis_fiyat_tipi TEXT,'
        'satis_fiyat_tipi TEXT,'
        'satis_fiyati1 INTEGER,'
        'satis_fiyati2 INTEGER,'
        'satis_fiyati3 INTEGER,'
        'satis_fiyati4 INTEGER,'
        'satis_fiyati5 INTEGER,'
        'alis_fiyati1 INTEGER,'
        'alis_fiyati2 INTEGER,'
        'alis_fiyati3 INTEGER,'
        'alis_fiyati4 INTEGER,'
        'alis_fiyati5 INTEGER,'
        'vade_alis1 INTEGER,'
        'vade_alis2 INTEGER,'
        'vade_alis3 INTEGER,'
        'vade_alis4 INTEGER,'
        'vade_alis5 INTEGER,'
        'vade_satis1 INTEGER,'
        'vade_satis2 INTEGER,'
        'vade_satis3 INTEGER,'
        'vade_satis4 INTEGER,'
        'vade_satis5 INTEGER,'
        'iskonto1 INTEGER,'
        'iskonto2 INTEGER,'
        'iskonto3 INTEGER,'
        'iskonto4 INTEGER,'
        'iskonto5 INTEGER,'       
        'iskonto6 INTEGER,'        
        'cari_vadesi_gelsin INTEGER,'
        'genel_iskonto_yuzde INTEGER,'
        'genel_iskonto REAL,'
        'alis_iskonto1 INTEGER,'
        'alis_iskonto2 INTEGER,'
        'alis_iskonto3 INTEGER,'
        'alis_iskonto4 INTEGER,'
        'alis_iskonto5 INTEGER,'       
        'alis_iskonto6 INTEGER,'
        'vade_alis_kodu1 TEXT,'
        'vade_alis_kodu2 TEXT,'
        'vade_alis_kodu3 TEXT,'
        'vade_alis_kodu4 TEXT,'
        'vade_alis_kodu5 TEXT,'
        'vade_satis_kodu1 TEXT,'
        'vade_satis_kodu2 TEXT,'
        'vade_satis_kodu3 TEXT,'
        'vade_satis_kodu4 TEXT,'
        'vade_satis_kodu5 TEXT,'
        'fiyat_listesi INTEGER,'
        'birim_fiyat_degistir INTEGER,'
        'gen_iskonto_degistir INTEGER,'
        'satir_iskonto_degistir INTEGER,'
        'borc_kapatma INTEGER,'
        'fat_basimi_yapilsin INTEGER,'
        'fat_seri_no TEXT,'
        'odeme_tarih_hesapla INTEGER,'
        'sak_kullanim_sekli INTEGER,'
        'sak_tablosu TEXT,'
        'toplu_mal_ayirma INTEGER,'
        'irsaliye_basimi INTEGER,'
        'irsaliye_seri_no TEXT,'
        'siparis_yapilsin INTEGER,'
        'kamyonlastirma_yapilsin INTEGER,'
        'irsaliye_yapilsin INTEGER,'
        'fatura_yapilsin INTEGER,'
        'kontrol_no TEXT,'
        'vade_degistir INTEGER,'
        'sts_irs_seri_no_rsayac INTEGER,'
        'sts_irs_basili_form_rsayac INTEGER,'
        'sts_fat_seri_no_rsayac INTEGER,'
        'sts_fat_basili_form_rsayac INTEGER,'
        'sts_fat_irs_basili_form_rsayac INTEGER,'
        'sts_iade_irsaliye_basimi INTEGER,'
        'sts_iade_irs_seri_no_rsayac INTEGER,'
        'sts_iade_irs_basili_form_rsayac INTEGER,'
        'sts_iade_fatura_basimi INTEGER,'
        'sts_iade_fat_seri_no_rsayac INTEGER,'
        'sts_iade_fat_basili_form_rsayac INTEGER '
        ')');

    }

  createtable3(Database db, int versiyon) async {
     await db.execute('CREATE TABLE SatisFiyatlari('
        'kod TEXT,'
        'fiyat_tipi TEXT,'
        'para_birimi TEXT,'
        'fiyat1 INTEGER,'
        'fiyat2 INTEGER,'
        'fiyat3 INTEGER,'
        'fiyat4 INTEGER,'
        'fiyat5 INTEGER,'
        'kdvli_fiyat1 INTEGER,'
        'kdvli_fiyat2 INTEGER,'
        'kdvli_fiyat3 INTEGER,'
        'kdvli_fiyat4 INTEGER,'
        'kdvli_fiyat5 INTEGER,'
        'vade1 INTEGER,'
        'vade2 INTEGER,'
        'vade3 INTEGER,'
        'vade4 INTEGER,'
        'vade5 INTEGER,'
        'iskonto1 INTEGER,'
        'iskonto2 INTEGER,'
        'iskonto3 INTEGER,'
        'iskonto4 INTEGER,'
        'iskonto5 INTEGER,'
        'iskonto6 INTEGER,'
        'genel_iskonto_yuzde INTEGER,'
        'genel_iskonto_tutar REAL,'
        'fiyat_tutar1 REAL,'
        'fiyat_tutar2 REAL,'
        'fiyat_tutar3 REAL,'
        'fiyat_tutar4 REAL,'
        'fiyat_tutar5 REAL,'
        'vade_kodu1 TEXT,'
        'vade_kodu2 TEXT,'
        'vade_kodu3 TEXT,'
        'vade_kodu4 TEXT,'
        'vade_kodu5 TEXT,'
        'iskonto_tutari1 REAL,'
        'iskonto_tutari2 REAL,'
        'iskonto_tutari3 REAL,'
        'iskonto_tutari4 REAL,'
        'iskonto_tutari5 REAL,'
        'iskonto_tutari6 REAL,'
        'indirim01_flag INTEGER,'
        'indirim02_flag INTEGER,'
        'indirim03_flag INTEGER,'
        'indirim04_flag INTEGER,'
        'indirim05_flag INTEGER,'
        'indirim06_flag INTEGER,'
        'cid TEXT,'
        'birim_fiyat_degistir INTEGER,'
        'gen_iskonto_degistir INTEGER,'
        'satir_iskonto_degistir INTEGER,'
        'vade_degistir INTEGER,'
        'ortalama_tarih_hesapla INTEGER,'
        'liste_adi TEXT,'
        'liste_birim TEXT,'
        'baz_birim TEXT,'
        'malzeme_kodu TEXT,'
        'satis_tipi TEXT, '
        'barkod TEXT,'
        'stok_miktari REAL,'
        'malzeme_adi TEXT,'
        'grup_adi1 TEXT,'
        'grup_adi2 TEXT,'
        'grup_adi3 TEXT,'
        'kdv_orani REAL '
       ')');

      await db.execute('CREATE TABLE StokFiyatListesi('
        'kod TEXT,'
        'fiyat_tipi TEXT,'
        'para_birimi TEXT,'
        'fiyat1 INTEGER,'
        'fiyat2 INTEGER,'
        'fiyat3 INTEGER,'
        'fiyat4 INTEGER,'
        'fiyat5 INTEGER,'
        'kdvli_fiyat1 INTEGER,'
        'kdvli_fiyat2 INTEGER,'
        'kdvli_fiyat3 INTEGER,'
        'kdvli_fiyat4 INTEGER,'
        'kdvli_fiyat5 INTEGER,'
        'vade1 INTEGER,'
        'vade2 INTEGER,'
        'vade3 INTEGER,'
        'vade4 INTEGER,'
        'vade5 INTEGER,'
        'iskonto1 INTEGER,'
        'iskonto2 INTEGER,'
        'iskonto3 INTEGER,'
        'iskonto4 INTEGER,'
        'iskonto5 INTEGER,'
        'iskonto6 INTEGER,'
        'genel_iskonto_yuzde INTEGER,'
        'genel_iskonto_tutar REAL,'
        'fiyat_tutar1 REAL,'
        'fiyat_tutar2 REAL,'
        'fiyat_tutar3 REAL,'
        'fiyat_tutar4 REAL,'
        'fiyat_tutar5 REAL,'
        'vade_kodu1 TEXT,'
        'vade_kodu2 TEXT,'
        'vade_kodu3 TEXT,'
        'vade_kodu4 TEXT,'
        'vade_kodu5 TEXT,'
        'iskonto_tutari1 REAL,'
        'iskonto_tutari2 REAL,'
        'iskonto_tutari3 REAL,'
        'iskonto_tutari4 REAL,'
        'iskonto_tutari5 REAL,'
        'iskonto_tutari6 REAL,'
        'indirim01_flag INTEGER,'
        'indirim02_flag INTEGER,'
        'indirim03_flag INTEGER,'
        'indirim04_flag INTEGER,'
        'indirim05_flag INTEGER,'
        'indirim06_flag INTEGER,'
        'cid TEXT,'
        'birim_fiyat_degistir INTEGER,'
        'gen_iskonto_degistir INTEGER,'
        'satir_iskonto_degistir INTEGER,'
        'vade_degistir INTEGER,'
        'ortalama_tarih_hesapla INTEGER,'
        'liste_adi TEXT,'
        'liste_birim TEXT,'
        'baz_birim TEXT,'
        'malzeme_kodu TEXT,'
        'satis_tipi TEXT, '
        'barkod TEXT,'
        'stok_miktari REAL,'
        'malzeme_adi TEXT,'
        'grup_adi1 TEXT,'
        'grup_adi2 TEXT,'
        'grup_adi3 TEXT,'
        'kdv_orani REAL '
       ')');


      await db.execute('CREATE TABLE Malzeme('
        'r_sayac INTEGER,'
        'malzeme_kodu TEXT,'
        'malzeme_adi TEXT,'
        'malzeme_sinifi_adi TEXT,'
        'malzeme_birimi TEXT,'
        'satinalma_birimi TEXT,'
        'satis_birimi TEXT,'
        'depo_birimi TEXT,'
        'cikis_birimi TEXT,'
        'birimi TEXT,'
        'malzeme_sinifi_no TEXT,'
        'kdv_orani REAL,'
        'dist_stok_kodu TEXT,'
        'baz_birim TEXT,'
        'path TEXT,'
        'yururlukten_kaldirildi INTEGER,'
        'grup_kodu1 TEXT,'
        'grup_adi1 TEXT,'
        'grup_kodu2 TEXT,'
        'grup_adi2 TEXT,'
        'grup_kodu3 TEXT,'
        'grup_adi3 TEXT,'
        'grup_kodu4 TEXT,'
        'grup_adi4 TEXT,'
        'grup_kodu5 TEXT,'
        'grup_adi5 TEXT,'
        'fatura_alti_indirimlere_dahil INTEGER '
      ')');

      await db.execute('CREATE TABLE BirimCevrimi('
        'r_sayac INTEGER,'
        'birim_rsayac INTEGER,'
        'birimden TEXT,'
        'birime TEXT,'
        'bolunen REAL,'
        'bolen REAL,'
        'malzeme_kodu TEXT '
      ')'); 
  }

  createtable4(Database db, int versiyon) async {
     await db.execute('CREATE TABLE MalzemePicture('        
        'path TEXT,'
        'malzeme_kodu TEXT,'
        'picture BLOB '        
      ')');

      await db.execute('CREATE TABLE Siparis('
        'r_sayac INTEGER PRIMARY KEY AUTOINCREMENT,'
        'cid TEXT,'
        'musteri_no TEXT,'
        'teslim_musteri_no TEXT,'
        'siparis_tarihi DATETIME,'
        'siparis_asama TEXT,'
        'satis_tipi TEXT,'
        'siparis_no INTEGER,'        
        'para_birimi TEXT,'
        'satis_temsilcisi TEXT,'
        'siparis_tutari REAL,'
        'toplam_tutar REAL,'
        'indirim_tutari REAL,'        
        'onay INTEGER,'
        'toplam_kdv REAL,'        
        'son_versiyon INTEGER,'
        'toplam_otv REAL,'
        'sub_fatura_tipi_id TEXT,'
        'tesis_no TEXT,'
        'depo_no TEXT,'
        'siparis_firma TEXT,'
        'aktarim_tipi TEXT,'
        'kullanici TEXT,'
        'stok_tipi_no TEXT,'
        'sevk_tarihi DATETIME,'
        'return_sayac INTEGER,'
        'sube_kodu TEXT,'
        'adres_tanimi_kod2 TEXT,'
        'adres_tanimi TEXT,'
        'android_gps_sayac INTEGER,'
        'aciklama TEXT,'        
        'siparis_form_aciklama TEXT,'
        'aciklama_android TEXT,'
        'guid TEXT '
        ')');

        await db.execute('CREATE TABLE SiparisSatir('
        'r_sayac INTEGER PRIMARY KEY AUTOINCREMENT,'
        'mus_rsayac INTEGER,'
        'cid TEXT,'
        'sira_no INTEGER,'
        'satir_id INTEGER,'
        'r_trg INTEGER,'
        'return_sayac INTEGER,'
        'sevk_plani_no INTEGER,'        
        'irsaliye_miktari REAL,'
        'masraf01 REAL,'
        'masraf02 REAL,'
        'masraf03 REAL,'
        'toplam_masraf REAL,'
        'masraflar TEXT,'
        'miscellenous_update INTEGER,'
        'malzeme_rsayac INTEGER,'
        'artan_miktar REAL,'
        'iade_miktari REAL,'
        'sevk_plani_miktari REAL,'
        'toplama_listesi_olustu INTEGER,'
        'alt_birim_adedi REAL,'
        'artan_top_sayisi INTEGER,'
        'toplama_listesi_top_sayisi INTEGER,'
        'kalan_top_sayisi INTEGER,'
        'proforma_no INTEGER,'
        'irsaliye_rsayac INTEGER,'
        'malzeme_kodu TEXT,'
        'birimi TEXT,'
        'birim_fiyat REAL,'
        'fiyat_tanimi_rsayac INTEGER,'
        'sevk_kalan_miktar REAL,'
        'miktar REAL,'
        'indirim TEXT,'
        'asama TEXT,'
        'sevk_tarihi DATETIME,'
        'teslim_tarihi DATETIME,'
        'fatura_edilen_miktar REAL,'
        'bedelsiz INTEGER,'
        'indirim01_flag INTEGER,'
        'indirim01 REAL,'
        'indirim02_flag INTEGER,'
        'indirim02 REAL,'
        'indirim03_flag INTEGER,'
        'indirim03 REAL,'
        'indirim04_flag INTEGER,'
        'indirim04 REAL,'
        'indirim05_flag INTEGER,'
        'indirim05 REAL,'
        'indirim06_flag INTEGER,'
        'indirim06 REAL,'
        'toplam_indirim REAL,'
        'std_doviz_kuru REAL,'
        'doviz_birim_fiyati REAL,'
        'doviz_tutar REAL,'
        'doviz_satir_tutari REAL,'
        'doviz_kdv_miktari REAL,'
        'satir_tutari REAL,'
        'sablon_kodu TEXT,'
        'kdv_orani REAL,'
        'kdv_tutari REAL,'
        'tutar REAL,'
        'depo_no TEXT,'
        'tesis_no TEXT,'
        'stok_tipi_no TEXT,'
        'grup_kodu TEXT,'

        'indirim_kodu TEXT,'
        'kolibasi_kampanya_flag INTEGER,'
        'bedelsiz_kampanya_flag INTEGER,'
        'yuzdesel_kampanya_flag INTEGER,'
        'depozito INTEGER,'
        'depozito_parent_id TEXT,'
        'depozito_sira_no INTEGER,'
        'kolibasi_kosul INTEGER,'
        'kolibasi_cari_kod TEXT,'
        'bedelsiz_tpr TEXT,'
        'bedelsiz_paket TEXT,'
        'aciklama TEXT '
        ')');

      await db.execute('CREATE TABLE BekleyenSiparis('
        'r_sayac INTEGER,'
        'mus_rsayac INTEGER,'
        'siparis_no INTEGER,'
        'cid TEXT,'
        'musteri_no TEXT,'
        'unvan TEXT,'
        'teslim_musteri_no TEXT,'
        'siparis_tarihi DATETIME,'
        'siparis_asama TEXT,'
        'satis_tipi TEXT,'
        'satis_tipi_adi TEXT,'
        'para_birimi TEXT,'
        'temsilci TEXT,'
        'temsilci_adi TEXT,'
        'siparis_tutari REAL,'
        'toplam_tutar REAL,'
        'indirim_tutari REAL,'
        'onay INTEGER,'
        'toplam_kdv REAL,'
        'toplam_otv REAL,'
        'sub_fatura_tipi_id TEXT,'
        'siparis_firma TEXT,'
        'aktarim_tipi TEXT,'
        'kullanici TEXT,'
        'sube_kodu TEXT,'
        'aciklama_android TEXT,'
        'sira_no INTEGER,'
        'malzeme_kodu TEXT,'
        'birimi TEXT,'
        'birim_fiyat REAL,'
        'miktar REAL,'
        'indirim TEXT,'
        'asama TEXT,'
        'sevk_tarihi DATETIME,'
        'teslim_tarihi DATETIME,'
        'fatura_edilen_miktar REAL,'
        'bedelsiz INTEGER,'
        'indirim01_flag INTEGER,'
        'indirim01 REAL,'
        'indirim02_flag INTEGER,'
        'indirim02 REAL,'
        'indirim03_flag INTEGER,'
        'indirim03 REAL,'
        'indirim04_flag INTEGER,'
        'indirim04 REAL,'
        'indirim05_flag INTEGER,'
        'indirim05 REAL,'
        'indirim06_flag INTEGER,'
        'indirim06 REAL,'
        'toplam_indirim REAL,'
        'satir_tutari REAL,'
        'sablon_kodu TEXT,'
        'kdv_orani REAL,'
        'kdv_tutari REAL,'
        'tutar REAL,'
        'depo_no TEXT,'
        'tesis_no TEXT,'
        'stok_tipi_no TEXT,'
        'grup_kodu TEXT,'
        'indirim_kodu TEXT,'
        'kolibasi_kampanya_flag INTEGER,'
        'malzeme_adi TEXT,'
        'grup_adi1 TEXT,'
        'grup_adi2 TEXT,'
        'grup_adi3 TEXT,'
        'baz_birim TEXT '
      ')');
  }

  createtable5(Database db, int versiyon) async {
      await db.execute('CREATE TABLE AllBekleyenSiparis('
        'r_sayac INTEGER,'
        'mus_rsayac INTEGER,'
        'siparis_no INTEGER,'
        'cid TEXT,'
        'musteri_no TEXT,'
        'unvan TEXT,'
        'teslim_musteri_no TEXT,'
        'siparis_tarihi DATETIME,'
        'siparis_asama TEXT,'
        'satis_tipi TEXT,'
        'satis_tipi_adi TEXT,'
        'para_birimi TEXT,'
        'temsilci TEXT,'
        'temsilci_adi TEXT,'
        'siparis_tutari REAL,'
        'toplam_tutar REAL,'
        'indirim_tutari REAL,'
        'onay INTEGER,'
        'toplam_kdv REAL,'
        'toplam_otv REAL,'
        'sub_fatura_tipi_id TEXT,'
        'siparis_firma TEXT,'
        'aktarim_tipi TEXT,'
        'kullanici TEXT,'
        'sube_kodu TEXT,'
        'aciklama_android TEXT,'
        'sira_no INTEGER,'
        'malzeme_kodu TEXT,'
        'birimi TEXT,'
        'birim_fiyat REAL,'
        'miktar REAL,'
        'indirim TEXT,'
        'asama TEXT,'
        'sevk_tarihi DATETIME,'
        'teslim_tarihi DATETIME,'
        'fatura_edilen_miktar REAL,'
        'bedelsiz INTEGER,'
        'indirim01_flag INTEGER,'
        'indirim01 REAL,'
        'indirim02_flag INTEGER,'
        'indirim02 REAL,'
        'indirim03_flag INTEGER,'
        'indirim03 REAL,'
        'indirim04_flag INTEGER,'
        'indirim04 REAL,'
        'indirim05_flag INTEGER,'
        'indirim05 REAL,'
        'indirim06_flag INTEGER,'
        'indirim06 REAL,'
        'toplam_indirim REAL,'
        'satir_tutari REAL,'
        'sablon_kodu TEXT,'
        'kdv_orani REAL,'
        'kdv_tutari REAL,'
        'tutar REAL,'
        'depo_no TEXT,'
        'tesis_no TEXT,'
        'stok_tipi_no TEXT,'
        'grup_kodu TEXT,'
        'indirim_kodu TEXT,'
        'kolibasi_kampanya_flag INTEGER,'
        'malzeme_adi TEXT,'
        'grup_adi1 TEXT,'
        'grup_adi2 TEXT,'
        'grup_adi3 TEXT,'
        'baz_birim TEXT '
      ')');

      await db.execute('CREATE TABLE Kampanya('
        'r_sayac INTEGER,'
        'kampanya_kodu TEXT,'
        'cid TEXT,'        
        'kampanya_adi TEXT,'
        'kampanya_tipi TEXT,'
        'baslangic_tarihi DATETIME,'
        'bitis_tarihi DATETIME,'
        'uygulama_bas_tarihi DATETIME,'
        'uygulama_bit_tarihi DATETIME,'
        'tah_maliyet REAL,'
        'tah_satis REAL,'
        'return_sayac INTEGER,'
        'modul_id INTEGER,'
        'indirim_yuzdesi REAL,'
        'ana_firma_kodu TEXT,'
        'kampanya_grubu TEXT,'
        'malzeme_sinifi TEXT,'
        'bayi_kampanya INTEGER,'
        'birim TEXT,'
        'kota REAL,'
        'bayi_sayisi INTEGER,'
        'musteri_sayisi INTEGER,'
        'bayi_bas_kota REAL,'
        'musteri_bas_kota REAL,'
        'asama TEXT,'
        'satilan REAL,'
        'mix_sarti_arama INTEGER,'
        'zorunlu INTEGER,'
        'grup_miktar_sarti INTEGER,'
        'grup_toplam_miktar REAL,'
        'aciklama TEXT,'
        'hayat_kampanya INTEGER,'
        'kontrat INTEGER,'
        'uretici_rsayac INTEGER,'
        'istisna_listesi_kullanildimi INTEGER,'
        'haric_tutulan_istisna_listesi INTEGER,'
        'cari_kodu TEXT'
      ')');


      await db.execute('CREATE TABLE KampanyaBedelsizSatir('
        'r_sayac INTEGER,'
        'kampanya_rsayac INTEGER,'
        'anlasma_durumu TEXT,'
        'birim TEXT,'
        'cari_kod TEXT,'
        'cid TEXT,'
        'dist TEXT,'
        'grup_kodu TEXT,'
        'grup_rsayac INTEGER,'
        'kademe TEXT,'
        'kalan_miktar REAL,'
        'Kota REAL,'
        'malzeme_kodu TEXT,'
        'malzeme_sinifi TEXT,'
        'miktar_sarti REAL,'
        'musteri_tipi TEXT,'
        'nokta_uygulama INTEGER,'
        'paket TEXT,'
        'satis_fiyati REAL,'
        'ust_grup TEXT,'
        'ust_paket TEXT '
      ')');

       await db.execute('CREATE TABLE KampanyaBedelsizVerilen('
        'r_sayac INTEGER,'
        'kampanya_rsayac INTEGER,'
        'birim TEXT,'
        'cid TEXT,'
        'grup_kodu TEXT,'
        'grup_rsayac INTEGER,'
        'hayat_kampanya INTEGER,'        
        'kota INTEGER,'
        'malzeme_kodu TEXT,'
        'miktar REAL,'
        'paket TEXT,'        
        'ust_paket TEXT,'
        'zorunlu INTEGER '
      ')');
  }

  createtable6(Database db, int versiyon) async {
     await db.execute('CREATE TABLE KampanyaYuzdeselSatir('
        'r_sayac INTEGER,'
        'kampanya_rsayac INTEGER,'
        'birim TEXT,'
        'cid TEXT,'
        'grup_kodu TEXT,'
        'indirim01 REAL,'
        'indirim02 REAL,'
        'indirim03 REAL,'
        'indirim04 REAL,'
        'indirim05 REAL,'
        'indirim06 REAL,'        
        'Kota REAL,'
        'malzeme_kodu TEXT,'
        'malzeme_sinifi TEXT,'
        'max_yuzde REAL,'
        'miktar_sarti REAL,'
        'nokta_uygulama INTEGER,'        
        'satis_fiyati REAL,'
        'yuzde REAL '
      ')');

      await db.execute('CREATE TABLE KampanyaSecimliGruplar('
        'r_sayac INTEGER,'
        'kampanya_rsayac INTEGER,'        
        'cid TEXT,'
        'grup_kodu TEXT,'
        'grup_adi TEXT,'
        'ana_grup_kodu TEXT,'
        'grup_toplam_miktar REAL,'
        'max_miktar REAL,'
        'bedelsiz_grup_toplam_miktar REAL,'
        'iskonto_hanesi INTEGER,'
        'min_miktar REAL,'
        'bayi_kota INTEGER,'
        'cari_kota INTEGER '
      ')');


     await db.execute('CREATE TABLE SiparisIndirim('
        'r_sayac INTEGER PRIMARY KEY AUTOINCREMENT,'
        'siparis_satir_rsayac INTEGER,'
        'indirim_kodu TEXT,'
        'indirim_yuzdesi REAL,'
        'siparis_rsayac INTEGER,'
        'sira_no INTEGER,'        
        'indirim_tutari REAL,'
        'vade_sablon TEXT,'
        'indirim_tipi TEXT,'
        'satilan REAL,'        
        'r_trg INTEGER,'        
        'indirim01 REAL,'
        'indirim02 REAL,'
        'indirim03 REAL,'
        'indirim04 REAL,'
        'indirim05 REAL,'
        'indirim06 REAL,'
        'grup_kodu TEXT '        
      ')');

      await db.execute('CREATE TABLE AktarimDurumu('        
        'r_sayac INTEGER PRIMARY KEY AUTOINCREMENT,'
        'aktarim_tarihi DATETIME '
      ')');
  }

  createtable7(Database db, int versiyon) async {
    await db.execute('CREATE TABLE MusteriMalAnalizi('        
        'r_sayac INTEGER PRIMARY KEY AUTOINCREMENT,'
        'musteri_kodu TEXT,'
        'malzeme_kodu TEXT,'
        'malzeme_adi TEXT,'
        'birimi TEXT,'
        'baz_birim TEXT,'
        'malzeme_sinifi_no TEXT,'
        'malzeme_sinifi_adi TEXT,'
        'grup_kodu1 TEXT,'
        'grup_kodu2 TEXT,'
        'grup_kodu3 TEXT,'
        'grup_kodu4 TEXT,'
        'grup_kodu5 TEXT,'
        'grup_adi1 TEXT,'
        'grup_adi2 TEXT,'
        'grup_adi3 TEXT,'
        'grup_adi4 TEXT,'
        'grup_adi5 TEXT,'
        'satis_tip_id TEXT,'
        'satis_tipi_adi TEXT,'
        'depo_no TEXT,'
        'depo_adi TEXT,'
        'rapor_birimi TEXT,'
        'satis_miktari  REAL,'
        'satis_brut_tutar  REAL,'
        'satis_indirim_tutari  REAL,'
        'satis_kdv_tutari  REAL,'
        'satis_masraf_tutari  REAL,'
        'satis_kdv_oncesi_tutar  REAL,'
        'satis_satir_tutari  REAL,'
        'iade_miktari  REAL,'
        'iade_brut_tutar  REAL,'
        'iade_indirim_tutari  REAL,'
        'iade_kdv_tutari  REAL,'
        'iade_kdv_oncesi_tutar  REAL,'
        'iade_satir_tutari  REAL,'
        'net_miktar  REAL,'
        'net_brut_tutar  REAL,'
        'net_indirim_tutari  REAL,'
        'net_kdv_tutari  REAL,'
        'net_kdv_oncesi_tutar  REAL,'
        'net_satir_tutari  REAL,'
        'tarih DATETIME'
      ')');

      await db.execute('CREATE TABLE AcikHesapListesi('        
        'Id INTEGER,'
        'cari_kodu TEXT,'
        'cari_unvan TEXT,'
        'fatura_no INTEGER,'
        'islem_tipi TEXT,'
        'fis_tarihi DATETIME,'
        'vade_gun_sayisi INTEGER,'
        'vade_tarihi DATETIME,'
        'borc_alacak TEXT,'
        'tefat_tutari REAL,'
        'tefat_bakiye_tutari REAL,'
        'bakiye_toplami REAL,'
        'tahsilat_gecikti TEXT,'
        'gecikme_gunu INTEGER,'
        'son_bakiye_bakod TEXT '
      ')');

      await db.execute('CREATE TABLE GunlukTahsilat('        
        'fis_no TEXT,'
        'cari_sayac INTEGER,'
        'fis_turu TEXT,'
        'tarih DATETIME,'
        'aktarim_temsilci TEXT,'
        'tl_alacak REAL,'
        'tl_borc REAL,'
        'kasa_kodu TEXT,'
        'sorumlu TEXT,'
        'cari_kodu TEXT,'
        'cari_unvan TEXT '
      ')');

      await db.execute('CREATE TABLE GunlukSiparis('        
        'malzeme_kodu TEXT,'
        'malzeme_adi TEXT,'        
        'baz_birim TEXT,'
        'depo_no TEXT,'
        'depo_adi TEXT,'
        'miktar REAL,'
        'satir_tutari REAL,'
        'grup_adi1 TEXT,'
        'grup_adi2 TEXT,'
        'grup_adi3 TEXT '

      ')');
  }
  

}